#!/bin/bash
origin=$(git config --get remote.origin.url)

function must()
{
    local v=$(git config --get $1)
    if ! [[ $v =~ $2 ]]
    then
        echo >&2 "$1=$v: must match $2"
        exit 1
    fi
}

case $origin in
git@gitlab.com[:/]*)
    must user.name hiraga-y
    must user.email hiraga-y@ml-fl.com
    ;;
esac
exit 0
