set nocompatible
set number
set termguicolors
set background=dark
set mouse=a
set list
set cul
set helplang=ja,en
let g:gruvbox_material_background = 'hard'
colorscheme gruvbox-material

set clipboard&
set clipboard^=unnamedplus
set expandtab
set shiftwidth=2
set softtabstop=2

" fzfはインストールしている前提
set rtp+=~/.fzf
set rtp+=~/code/v9filer.vim

let g:v9filer_nerd_font_icons=v:true
