set nocompatible
set number
set termguicolors
set background=dark
set mouse=a
set list
set cul
set helplang=ja,en
let g:gruvbox_material_background = 'hard'
colorscheme gruvbox-material

" fzfはインストールしている前提
set rtp+=~/.fzf
set rtp+=~/code/v9filer.vim

